name: .env Exists
abbreviation: envexists
checker: PragmaRX\Health\Checkers\DirectoryAndFilePresence
file_exists:
  - "{{ base_path('.env') }}"
file_do_not_exists:
directory_exists:
directory_do_not_exists:
notify: true
error_message: 'The .env file does not exists'
column_size: 4
