name: Cache
abbreviation: csh
checker: PragmaRX\Health\Checkers\Cache
notify: true
error_message: "Cache is not returning cached values."
column_size: 3
targets:
  - default:
      seconds: 60
      key: health-cache-test
