name: Configuration Cached
abbreviation: cfgcch
checker: PragmaRX\Health\Checkers\Expression
notify: true
column_size: 3
error_message: "Configuration is not cached"
targets:
  - default:
      expression_value: "app()->configurationIsCached()"
      should_return: true
