name: Debug Mode on Production
abbreviation: debug
checker: PragmaRX\Health\Checkers\Expression
notify: true
column_size: 3
error_message: "Application is in debug mode"
targets:
  - default:
      expression_value: "!app()->environment('production') || !app('config')->get('app.debug')"
      should_return: true
