name: Debug Mode
abbreviation: debug
checker: PragmaRX\Health\Checkers\Expression
notify: true
column_size: 3
error_message: "Application is in debug mode"
targets:
  - default:
      expression_value: "app('config')->get('app.debug')"
      should_return: false
