name: Disk Space
abbreviation: dskspc
checker: PragmaRX\Health\Checkers\DiskSpace
notify: true
column_size: 2
targets:
  - default:
      name: root
      path: "/"
      minimum: 1GB
      message:
        "Volume %s is getting out of space. It has %s when it should have at least %s."
