name: DocuSign
abbreviation: dcsgn
checker: PragmaRX\Health\Checkers\Docusign
column_size: 3
notify: true
error_message: "A reboot is required in this server (Uptime Checker)"
targets:
  - default:
      username: "{{ docusign.username }}"
      password: "{{ docusign.password }}"
      integrator_key: "{{ docusign.integrator_key }}"
      debug: "{{ docusign.debug }}"
      debug_file: storage/logs/docusign.log
      api_host: "{{ docusign.host }}"
      not_installed_message: "Docusign is not installed."
