name: Elasticsearch Connectable
abbreviation: redisconn
checker: PragmaRX\Health\Checkers\PortCheck
description: "Check if Elasticsearch port is connectable."
notify: true
column_size: 3
error_message: "Could not connect to %s on port %s"
targets:
  - localhost:
      hostname: localhost
      port: 9200
      timeout: 2
