name: Filesystem
abbreviation: flstm
checker: PragmaRX\Health\Checkers\Filesystem
description: "Temp files creating for system directory 'sys_get_temp_dir()'."
notify: true
column_size: 3
targets:
  - default:
      error_message: "Unable to create temp file: %s."
