name: Https
abbreviation: https
checker: PragmaRX\Health\Checkers\Https
notify: true
column_size: 3
timeout_message: "[TIMEOUT] A request to %s took %s seconds. Timeout is set to %s seconds."
connection_timeout: 30
roundtrip_timeout: 30
targets:
  - default:
      urls:
        - '{{ config("app.url") }}'
        - https://google.com
        - https://yahoo.com:
            headers:
              Authorization: Basic aHR0cEBmb25kYXRpb25sb3Vpc3Z1aXR0b24uZnI6Z29hdC13ZWVkeQ==
