name: Http
abbreviation: http
checker: PragmaRX\Health\Checkers\Http
notify: true
column_size: 3
timeout_message: "[TIMEOUT] A request to %s took %s seconds. Timeout is set to %s seconds."
connection_timeout: 30
roundtrip_timeout: 30
targets:
  - default:
      urls:
        - '{{ config("app.url") }}'
        - http://google.com
