name: LaravelServices
abbreviation: lvs
checker: PragmaRX\Health\Checkers\HttpsChecker
notify: true
connection_timeout: 2
roundtrip_timeout: 4
timeout_message: '[TIMEOUT] A request to %s took %s seconds. Timeout is set to %s.'
url:
    - 'https://forge.laravel.com'
    - 'https://envoyer.io'
column_size: 4

