name: Memcached Connectable
abbreviation: redisconn
checker: PragmaRX\Health\Checkers\PortCheck
notify: true
column_size: 3
error_message: "Could not connect to %s on port %s"
targets:
  - default:
      hostname: localhost
      port: 11211
      timeout: 2
