name: Migrations Up to Date
abbreviation: debug
checker: PragmaRX\Health\Checkers\Artisan
notify: true
column_size: 3
error_message: "Not all migrations were migrated"
targets:
  - default:
      command:
        name: "migrate"
        options:
          "--pretend": true
          "--force": true
      should_return: "Nothing to migrate"
