name: MySQL Connectable
abbreviation: mysqlgrsqlsrvrconn
checker: PragmaRX\Health\Checkers\PortCheck
notify: true
column_size: 3
error_message: "Could not connect to %s on port %s"
targets:
  - default:
      name: localhost
      hostname: localhost
      port: 3306
      timeout: 2
