name: PostgreSQL Connectable
abbreviation: pstgrsqlsrvrconn
checker: PragmaRX\Health\Checkers\PortCheck
ports:
  server1:
    hostname: localhost
    port: 5432
    timeout: 2
notify: true
column_size: 4
error_message: "Could not connect to %s on port %s"
