name: PostgreSQL Connectable
abbreviation: pstgrsqlsrvrconn
checker: PragmaRX\Health\Checkers\PortCheck
notify: true
column_size: 3
error_message: "Could not connect to %s on port %s"
targets:
  - default:
      hostname: localhost
      port: 5432
      timeout: 2
