name: Queue
abbreviation: queue
checker: PragmaRX\Health\Checkers\Queue
description: "Test job should be successfully handled."
error_message: "Queue system is not working properly."
column_size: 3
targets:
  - default:
      test_job: PragmaRX\Health\Support\Jobs\TestJob
      cache_instance: cache
      notify: true
      connection: ""
