name: QueueWorkers
abbreviation: qwrkrs
checker: PragmaRX\Health\Checkers\Process
notify: true
column_size: 3
targets:
  - default:
      command: "ps aux | grep php | grep queue:work"
      method: process_count
      process_name: php
      pid_file: ""
      instances:
        minimum:
          count: 1
          message:
            'Process "%s" has not enough instances running: it has %s, when should have at least %s'
        maximum:
          count: 3
          message:
            'Process "%s" exceeded the maximum number of running instances: it has %s, when should have at most %s'
      pid_file_missing_error_message: "Process ID file is missing: %s."
      pid_file_missing_not_locked:
        "Process ID file is not being used by any process: %s."
