name: RebootRequired
abbreviation: rbtrqrd
checker: PragmaRX\Health\Checkers\DirectoryAndFilePresence
notify: true
error_message: "A reboot is required in this server (Uptime Checker)"
column_size: 3
targets:
  - default:
      file_exists:
      file_do_not_exists:
        - /var/run/reboot-required
      directory_exists:
      directory_do_not_exists:
