name: Packages Security Checker
abbreviation: debug
checker: PragmaRX\Health\Checkers\SecurityChecker
notify: true
column_size: 4
error_message: 'The following packages have vulnerabilities referenced in the SensioLabs security advisories database: %s'
