name: ServerUptime
abbreviation: uptm
checker: PragmaRX\Health\Checkers\ServerUptime
column_size: 3
notify: true
error_message:
  'Looks like your server was recently rebooted, current uptime is now "%s" and it was "%s" before restart.'
targets:
  - default:
      regex:
        '~(?<time_hour>\d{1,2}):(?<time_minute>\d{2})(?::(?<time_second>\d{2}))?\s+up\s+(?:(?<up_days>\d+)\s+days?,\s+)?\b(?:(?<up_hours>\d+):)?(?<up_minutes>\d+)(?:\s+(?:minute|minutes|min)?)?,\s+(?<users>\d+)?.+?(?<load_1>\d+.\d+),?\s+(?<load_5>\d+.\d+),?\s+(?<load_15>\d+.\d+)~'
      command: "uptime 2>&1"
      save_to: "{{ storage_path('app') }}/uptime.json"
      action_message: "Your server was rebooted (Uptime Checker)"
