name: ServerLoad
abbreviation: load
checker: PragmaRX\Health\Checkers\ServerLoad
error_message:
  'Your server might be overloaded, current server load values are "%s, %s and %s", which are above the threshold values: "%s, %s and %s".'
column_size: 3
notify: true
targets:
  - default:
      regex:
        '~(?<time_hour>\d{1,2}):(?<time_minute>\d{2})(?::(?<time_second>\d{2}))?\s+up\s+(?:(?<up_days>\d+)\s+days?,\s+)?\b(?:(?<up_hours>\d+):)?(?<up_minutes>\d+)(?:\s+(?:minute|minutes|min)?)?,\s+(?<users>\d+).+?(?<load_1>\d+.\d+),?\s+(?<load_5>\d+.\d+),?\s+(?<load_15>\d+.\d+)~'
      command: "uptime 2>&1"
      max_load:
        load_1: 2
        load_5: 1.5
        load_15: 1
      action_message: "Too much load! (Server Load Checker)"
