name: Sshd
abbreviation: sshd
checker: PragmaRX\Health\Checkers\Process
column_size: 3
notify: true
targets:
  - default:
      command: "pgrep %s"
      method: process_count
      process_name: sshd
      pid_file: ""
      instances:
        minimum:
          count: 1
          message:
                  'Process "%s" has not enough instances running: it has %s, when should have at least %s'
        maximum:
          count: 15
          message:
                  'Process "%s" exceeded the maximum number of running instances: it has %s, when should have at most %s'
      pid_file_missing_error_message: "Process ID file is missing: %s."
      pid_file_missing_not_locked:
        "Process ID file is not being used by any process: %s."
